receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318

processors:
  source_map_symbolicator:
  proguard_symbolicator:
  dsym_symbolicator:
  batch:
  memory_limiter:
    check_interval: 1s
    limit_mib: 4000

exporters:
  debug:
    verbosity: detailed

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [memory_limiter, batch, source_map_symbolicator]
      exporters: [debug]
    logs:
      receivers: [otlp]
      processors: [memory_limiter, batch, proguard_symbolicator, dsym_symbolicator]
      exporters: [debug]
  telemetry:
    logs:
      level: debug
