version: 2.1

orbs:
  docker: circleci/docker@2.8.2

workflows:
  version: 2
  build-and-push-workflow:
    jobs:
      - docker/publish:
          context: Honeycomb Secrets for Public Repos
          executor:
            name: docker/machine
            resource-class: medium
          deploy: false
          image: honeycombio/honeycomb-opentelemetry-collector
          tag: x86_64-${CIRCLE_SHA1}
      - docker/publish:
          context: Honeycomb Secrets for Public Repos
          executor:
            name: docker/machine
            resource-class: arm.medium
          deploy: false
          image: honeycombio/honeycomb-opentelemetry-collector
          tag: arm64-${CIRCLE_SHA1}
