version: 2.1

executors:
  docker-executor:
    docker:
      - image: cimg/base:stable
        user: root

jobs:
  build-and-push-multiarch:
    executor: docker-executor
    resource_class: xlarge
    steps:
      - checkout
      - setup_remote_docker:
          # version: 20.10.7
          privileged: true  # Required for Buildx
      - run:
          name: Install QEMU for Multi-Arch Builds
          command: |
            docker run --rm --privileged tonistiigi/binfmt --install all
      - run:
          name: Set up Docker Buildx
          command: |
            docker buildx create --use --name multiarch_builder
            docker buildx inspect --bootstrap  # Ensures everything is set up correctly
            make build-docker
      # - run:
      #     name: Login to Docker Hub
      #     command: echo $DOCKERHUB_PASSWORD | docker login -u $DOCKERHUB_USERNAME --password-stdin
      # - run:
      #     name: Build and Push Multi-Arch Docker Image
      #     command: |
      #       docker buildx build \
      #         --platform linux/amd64,linux/arm64 \
      #         --push \
      #         -t $DOCKERHUB_USERNAME/$IMAGE_NAME:$CIRCLE_SHA1 \
      #         -t $DOCKERHUB_USERNAME/$IMAGE_NAME:latest \
              # .
workflows:
  version: 2
  build-and-push-workflow:
    jobs:
      - build-and-push-multiarch