version: 2.1

orbs:
  docker: circleci/docker@2.8.2

workflows:
  version: 2
  build-and-push-workflow:
    jobs:
      - docker/publish:
          context: Honeycomb Secrets for Public Repos
          deploy: false
          image: honeycombio/honeycomb-opentelemetry-collector
          tag: $CIRCLE_SHA1,$CIRCLE_TAG,latest
