version: 2.1

orbs:
  docker: circleci/docker@2.8.2
  aws-ecr: circleci/aws-ecr@9.5.4

executors:
  docker-executor:
    docker:
      - image: cimg/base:current
        user: root

jobs:
  build-and-push-multiarch:
    executor: docker-executor
    resource_class: xlarge
    steps:
      - checkout
      - setup_remote_docker:
          privileged: true  # Required for Buildx
      - run:
          no_output_timeout: 30m
          name: Set up Docker Buildx
          command: |
            docker buildx create --use --name multiarch_builder
            docker buildx inspect --bootstrap  # Ensures everything is set up correctly
      - run:
          name: Login to Docker Hub
          command: echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin
      - aws-ecr/ecr_login:
          public_registry: true
      - run:
          name: Build and Push Multi-Arch Docker Image to Docker Hub and Public ECR
          command: |
            docker buildx build \
              --platform linux/amd64,linux/arm64 \
              --sbom=true \
              --provenance=true \
              --push \
              -t honeycombio/honeycomb-opentelemetry-collector:$CIRCLE_SHA1 \
              -t honeycombio/honeycomb-opentelemetry-collector:$CIRCLE_TAG \
              -t honeycombio/honeycomb-opentelemetry-collector:latest \
              -t public.ecr.aws/honeycombio/honeycomb-opentelemetry-collector:$CIRCLE_SHA1 \
              -t public.ecr.aws/honeycombio/honeycomb-opentelemetry-collector:$CIRCLE_TAG \
              -t public.ecr.aws/honeycombio/honeycomb-opentelemetry-collector:latest \
              .
      - docker/update-description:
          docker-username: DOCKER_USERNAME
          docker-password: DOCKER_PASSWORD
          image: honeycombio/honeycomb-opentelemetry-collector
workflows:
  version: 2
  build-and-push-workflow:
    jobs:
      - build-and-push-multiarch:
          context: Honeycomb Secrets for Public Repos
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/
